# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[Î»](bold green)"
error_symbol = "[Î»](bold red)"
vicmd_symbol = "[Î»](bold green)"

[cmd_duration]
disabled = true

[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[nodejs]
disabled = true

[directory]
style  = "red"
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = true
truncation_length = 1

[git_status]
format = " [$all_status$ahead_behind]($style) "
all_status = "$conflicted$stashed$deleted$renamed$modified$staged$untracked"
ahead_count = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind_count = "â‡£${count}"
style = 'yellow dimmed'
untracked =  ""
stashed =  ""

[git_branch]
format = "\\[[$symbol$branch]($style)\\]"
symbol = 'â‡ '
style = 'green'

[git_state]
disabled = true
format = "[\\($state( $progress_current of $progress_total)\\)]($style) "

[ruby]
disabled = true
symbol = "ğŸ”º"

[jobs]
disabled = true


